### ISSUE TITLE
Showing Hashtag Count

### ISSUE THREAD

**Issue by licatajustin** [ralovely/simple_hashtag#2]
First of all, this gem works great, well done.

This is more of a question and less of an issue. On the view page, when you loop through the model's hashtags to display them and link to the respective tags page, how can i display the total number of that tags count?

Say this post has two hashtags, design & ui. Design has been tagged 20 times on the site and ui has been tagged 6 times. How can i display that in the loop??

I got it to work on the 'show' page where you show all posts with the respective tags but not on the page where i'm looping through the model's hashtags. 

I wanted to ask you guys before I took to StackOverflow, even though i know these are supposed to be issues, so i apologize for that. Again, well done on the gem.

**Comment by ralovely** [comment]
Hi @licatajustin.
Thanks.

If you are talking about the hashtags/index view,
you just have to add a count to `hashtag.hashtaggings`, like:

``` erb
<h1>Hashtags</h1>
<ul>
<% @hashtags.each do |hashtag| %>
  <li><%= link_to hashtag.name, hashtag_path(hashtag.name) %> (<%= hashtag.hashtaggings.count %>)</li>
<% end -%>
</ul>
```

You might want to `includes(:hashtaggings)` in your request to let Arel optimize the SQL:

``` ruby
  def index
    @hashtags = SimpleHashtag::Hashtag.includes(:hashtaggings).all
  end
```

```
```

**Comment by licatajustin** [comment]
Thanks a ton for the reply and for the gem @ralovely.

That did the trick. Works like a charm.
