### ISSUE TITLE
Tags doesn't delete when Object is deleted

### ISSUE THREAD

**Issue by licatajustin** [ralovely/simple_hashtag#3]
When deleting the object that is tagged, the hashtag isn't deleted with it. Say I had an Article model where you can make articles and tag them. If you make two articles that both have the same hashtag and delete one of the articles, the db still shows two hashtags and when you view those hashtags you get the error because it's trying to find an article that doesn't exist.

**Comment by ralovely** [comment]
Thanks @licatajustin 
I fixed it with https://github.com/ralovely/simple_hashtag/commit/4e8832a845258f1d1d55db404975cc6b49eb12fe
0.1.9 is pushed with the fix.

**Comment by licatajustin** [comment]
Well done...thank you!
