### ISSUE TITLE
Support for hashtag link in model's attribute

### ISSUE THREAD

**Issue by licatajustin** [ralovely/simple_hashtag#5]
Say you create hashtags in a model's attribute, description. When showing that description on the model's view page, the hashtags are just text, not links to the respective hashtag page. Will there be support for this added feature??

**Comment by ralovely** [comment]
Hi @licatajustin 

it is supported already.
When you generate the views, 
`rails g simple_hashtag:views`
it will generate a helper with a method:
`linkify_hashtags` for this very purpose.

You can see it here: https://github.com/ralovely/simple_hashtag/blob/master/lib/generators/simple_hashtag/templates/views/hashtags_helper.rb

Was it what you were searching ?

The README is not clear enough on that point.
I will update it.

**Comment by licatajustin** [comment]
Yes that's exactly what I was talking about. I must have forgot to run the generator because I didn't have the helper. Got it now though thank you! Cheers
